CREATE SCHEMA IF NOT EXISTS Person;

CREATE SCHEMA IF NOT EXISTS HumanResources;

CREATE SCHEMA IF NOT EXISTS Production;

CREATE SCHEMA IF NOT EXISTS Purchasing;

CREATE SCHEMA IF NOT EXISTS Sales;

CREATE SCHEMA IF NOT EXISTS dbo;
